<?php

/**
 * @file
 * Contains social_pages.module.
 *
 * @todo
 * - Make ordering the networks draggable?
 * - Allow adding your own networks?
 */

use Drupal\Core\Routing\RouteMatchInterface;

/**
 * Implements hook_help().
 */
function social_pages_help($route_name, RouteMatchInterface $route_match) {
  switch ($route_name) {
    // Main module help for the social_pages module.
    case 'help.page.social_pages':
      $output = '';
      $output .= '<h3>' . t('About') . '</h3>';
      $output .= '<p>' . t('Field for adding social media links to entities') . '</p>';
      return $output;

    default:
  }
}

function social_pages_field_options() {
  foreach (_social_pages_field_defintions() as $key => $item) {
    $options[$key] = $item['title'];
  }
  return $options;
}

function _social_pages_field_defintions() {
  return [
    'instagram' => [
      'title' => 'Instagram',
      'prefix' => '@',
      'suffix' => NULL,
      'placeholder' => 'Instagram username',
      'description' => NULL,
      'type' => 'string',
      'pattern' => '/^[A-Za-z0-9_\.]+$/',
      'type_label' => 'username',
      'render_pattern' => 'https://instagram.com/!value',
      'icon' => 'instagram',
      'field' => [
        'type' => 'varchar',
        'length' => 70,
        'not null' => FALSE,
      ],
    ],
    'facebook' => [
      'title' => 'Facebook',
      'prefix' => NULL,
      'suffix' => NULL,
      'placeholder' => 'Full facebook url',
      'description' => NULL,
      'type' => 'url',
      'pattern' => '!^(http://|https://)?(www\.)?facebook\.com/[a-zA-Z0-9]+!',
      'render_pattern' => '!value',
      'icon' => 'facebook',
      'field' => [
        'type' => 'text',
        //'length' => 2048,
        'not null' => FALSE,
      ],
    ],
    'twitter' => [
      'title' => 'Twitter',
      'prefix' => '@',
      'suffix' => NULL,
      'placeholder' => 'Twitter username',
      'description' => NULL,
      'type' => 'string',
      'pattern' => '/^[A-Za-z0-9_]+$/',
      'type_label' => 'username',
      'render_pattern' => 'https://twitter.com/!value',
      'icon' => 'twitter',
      'field' => [
        'type' => 'text',
        //'length' => 2048,
        'not null' => FALSE,
      ],
    ],
    'linkedin' => [
      'title' => 'Linked In',
      'prefix' => NULL,
      'suffix' => NULL,
      'placeholder' => 'Full LinkedIn URL',
      'description' => NULL,
      'type' => 'url',
      'pattern' => '!^(http://|https://)?(www\.)?linkedin\.com/[a-zA-Z0-9]+!',
      'render_pattern' => '!value',
      'icon' => 'linkedin',
      'field' => [
        'type' => 'text',
        //'length' => 2048,
        'not null' => FALSE,
      ],
    ],
    'flickr' => [
      'title' => 'Flickr',
      'prefix' => NULL,
      'suffix' => NULL,
      'placeholder' => 'Full Flickr URL',
      'description' => NULL,
      'type' => 'url',
      'pattern' => '!^(http://|https://)?(www\.)?flickr\.com/[a-zA-Z0-9]+!',
      'render_pattern' => '!value',
      'icon' => 'flickr',
      'field' => [
        'type' => 'varchar',
        'length' => 255,
        'not null' => FALSE,
      ],
    ],
    'youtube' => [
      'title' => 'YouTube',
      'prefix' => NULL,
      'suffix' => NULL,
      'placeholder' => 'YouTube Channel URL',
      'description' => NULL,
      'type' => 'url',
      'pattern' => '!^(http://|https://)?(www\.)?youtube\.com/[a-zA-Z0-9]+!',
      //'!^(http://|https://)?(www\.)?youtube\.com/(user|channel|c|u)/[a-zA-Z0-9]+!',
      'render_pattern' => '!value',
      'icon' => 'youtube',
      'field' => [
        'type' => 'text',
        //'length' => 2048,
        'not null' => FALSE,
      ],
    ],
    'vimeo' => [
      'title' => 'Vimeo',
      'prefix' => NULL,
      'suffix' => NULL,
      'placeholder' => 'Vimeo username',
      'description' => NULL,
      'type' => 'string',
      'pattern' => '/^[A-Za-z0-9_]+$/',
      'type_label' => 'username',
      'render_pattern' => 'https://vimeo.com/!value',
      'icon' => 'vimeo',
        'type' => 'varchar',
        'length' => 70,
        'not null' => FALSE,
      ],
    ],
    'fpx' => [
      'title' => '500px',
      'prefix' => NULL,
      'suffix' => NULL,
      'placeholder' => '500px username',
      'description' => NULL,
      'type' => 'string',
      'pattern' => '/^[A-Za-z0-9_-]+$/',
      'type_label' => 'username',
      'render_pattern' => 'https://500px.com/!value',
      'icon' => '500px',
      'field' => [
        'type' => 'varchar',
        'length' => 70,
        'not null' => FALSE,
      ],
    ],
    'snapchat' => [
      'title' => 'Snapchat',
      'prefix' => NULL,
      'suffix' => NULL,
      'placeholder' => 'Snapchat username',
      'description' => NULL,
      'type' => 'string',
      'pattern' => '/^[\.A-Za-z0-9_-]+$/',
      'type_label' => 'username',
      'render_pattern' => 'https://snapchat.com/add/!value',
      'icon' => 'snapchat',
      'field' => [
        'type' => 'varchar',
        'length' => 70,
        'not null' => FALSE,
      ],
    ],
    'pinterest' => [
      'title' => 'Pinterest',
      'prefix' => '@',
      'suffix' => NULL,
      'placeholder' => 'Pinterest username',
      'description' => NULL,
      'type' => 'string',
      'pattern' => '/^[A-Za-z0-9_]+$/',
      'type_label' => 'username',
      'render_pattern' => 'https://www.pinterset.com/!value',
      'icon' => 'pinterest',
      'field' => [
        'type' => 'varchar',
        'length' => 70,
        'not null' => FALSE,
      ],
    ],
  ];

}
/**
 * Implementing hook_theme().
 */
function social_pages_theme($existing, $type, $theme, $path) {
  return [
    'social_pages_network' => [
      'variables' => [
        'info' => [],
        'id' => NULL,
        'url' => NULL,
        'icon' => NULL,
        'value' => NULL,
        'title' => NULL,
        'display' => [],
        'link' => TRUE,
        'content' => [],
      ],
    ],
  ];
}

function template_preprocess_social_pages_network(&$vars) {
  $vars['attributes']['class'][] = $vars['id'];
  $vars['attributes']['class'][] = 'social-page-link';
  $vars['content'] = [];
  foreach ($vars['display'] as $el) {
    switch ($el) {
      case 'icons':
        $vars['content']['icon'] = [
          '#theme' => 'svg_icon',
          '#style' => 'brands',
          '#name' => $vars['info']['icon'],
          '#attributes' => ['class' => ['social-icon', 'fw']],
        ];
        break;
      case 'title':
        $vars['content']['title']['#markup'] = t('Follow on @network', ['@network' => $vars['title']]);
        break;
      case 'url':
        $vars['content']['url']['#markup'] = $vars['url'];
        break;
      case 'handle':
        $parts = explode('/', $vars['value']);
        $handle = array_pop($parts);
        $handle = '@' . trim($handle, '@');
        $vars['content']['handle']['#markup'] = $handle;
        break;
    }
  }
}
